In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
iris_df=pd.read_csv('data/iris.csv')
iris_df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/iris.csv'

In [12]:
from sklearn.datasets import load_iris
iris1=load_iris()
iris1_df=pd.DataFrame(data=iris1.data, columns=iris1.feature_names)
iris1_df['target'] = iris1.target
iris1_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [13]:
import seaborn as sns
sns.get_dataset_names()
iris2_df=sns.load_dataset('iris')
iris2_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
iris_df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa